Update build VM to build buster

diff --git a/roles/hypervisor/templates/build_vm b/roles/hypervisor/templates/build_vm
--- a/roles/hypervisor/templates/build_vm
+++ b/roles/hypervisor/templates/build_vm
@@ -1,13 +1,12 @@
 #!/bin/bash
-
 # Configs overwritable via environment variables
-VSYSTEM=${VSYSTEM:=qemu}                                        # Either 'qemu' or 'kvm'
-FLAVOUR=${FLAVOUR:=debian}                                      # Either 'debian' or 'ubuntu'
+VSYSTEM=${VSYSTEM:=qemu}         # Either 'qemu' or 'kvm'
+FLAVOUR=${FLAVOUR:=debian}       # Either 'debian' or 'ubuntu'
 INCLUDES=${INCLUDES:="less,vim,sudo,openssh-server,acpid,dbus"}
-MIRROR=${MIRROR:="http://ftp.hu.debian.org/debian"}
 ARCH=${ARCH:=amd64}
-APT_CACHER=${APT_CACHER:=no}
 IMGSIZE=${IMGSIZE:=80G}
+RELEASE=buster
+HOSTNAME=myserver
 
 clean_debian() {
         echo "Cleaning up.."
@@ -31,33 +30,24 @@ cancel() {
         fail "CTRL-C detected"
 }
 
-if [ $# -lt 3 ]
+if [ $# -lt 1 ]
 then
         echo "author: Kamil Trzcinski (http://ayufan.eu)"
         echo "license: GPL"
-        echo "usage: $0 <image-file> <hostname>" 1>&2
+        echo "usage: $0 <image-file>" 1>&2
         exit 1
 fi
 
 FILE=$1
-HOSTNAME=$2
-RELEASE=$3
-shift 3
 
 trap cancel INT
 
 echo "Installing $RELEASE into $FILE..."
 
-MNT_DIR=`tempfile`
+MNT_DIR=`mktemp`
 rm $MNT_DIR
 mkdir $MNT_DIR
 DISK=
-
-# add apt cacher for faster rebuilds, runs on 3142
-if [ "$APT_CACHER" == "yes" ]; then
-    echo "Installing apt-cacher-ng for fast rebuilds"
-    apt-get install apt-cacher-ng
-fi
 
 if [ ! -f $FILE ]; then
     echo "Creating $FILE"
@@ -90,32 +80,37 @@ echo "Connected $FILE to $DISK"
 echo "Partitioning $DISK..."
 sfdisk $DISK << EOF || fail "cannot partition $FILE"
 ,200MiB,83,*
+,4GiB,S
 ;
 EOF
 
 echo "Creating boot partition..."
 mkfs.ext4 -q ${DISK}p1 || fail "cannot create /boot ext4"
 
+echo "Creating boot partition..."
+mkswap ${DISK}p2 || fail "cannot create swap"
+
 echo "Creating root partition..."
-mkfs.ext4 -q ${DISK}p2 || fail "cannot create / ext4"
+mkfs.ext4 -q ${DISK}p3 || fail "cannot create / ext4"
 
 echo "Mounting root partition..."
-mount ${DISK}p2 $MNT_DIR || fail "cannot mount /"
+mount ${DISK}p3 $MNT_DIR || fail "cannot mount /"
 
 echo "Installing Debian..."
-debootstrap --include=$INCLUDES $* stable $MNT_DIR || fail "cannot install $RELEASE into $DISK"
+debootstrap --cache-dir /tmp/aptcache --include=$INCLUDES $RELEASE $MNT_DIR || fail "cannot install onto $DISK"
 
 echo "Configuring system..."
 cat <<EOF > $MNT_DIR/etc/fstab
-/dev/vda1 /boot               ext4    sync 0       2
-/dev/vda2 /                   ext4    errors=remount-ro 0       1
+/dev/vda1 /boot ext4 sync              0 2
+/dev/vda2 swap  swap defaults          0 0
+/dev/vda3 /     ext4 errors=remount-ro 0 1
 EOF
 
 echo $HOSTNAME > $MNT_DIR/etc/hostname
 
 cat <<EOF > $MNT_DIR/etc/hosts
 127.0.0.1       localhost
-127.0.1.1               $HOSTNAME
+127.0.1.1       $HOSTNAME
 
 # The following lines are desirable for IPv6 capable hosts
 ::1     localhost ip6-localhost ip6-loopback
@@ -137,8 +132,12 @@ mount --bind /dev/ $MNT_DIR/dev || fail "cannot bind /dev"
 chroot $MNT_DIR mount -t ext4 ${DISK}p1 /boot || fail "cannot mount /boot"
 chroot $MNT_DIR mount -t proc none /proc || fail "cannot mount /proc"
 chroot $MNT_DIR mount -t sysfs none /sys || fail "cannot mount /sys"
+
+echo "Installing $BOOT_PKG in chroot"
 LANG=C DEBIAN_FRONTEND=noninteractive chroot $MNT_DIR apt-get install -y --force-yes -q $BOOT_PKG || fail "cannot install $BOOT_PKG"
-chroot $MNT_DIR grub-install $DISK || fail "cannot install grub"
+
+echo "Running grab-install in chroot"
+chroot $MNT_DIR sudo -i grub-install $DISK || fail "cannot install grub"
 
 cat <<EOF > $MNT_DIR/etc/default/grub
 GRUB_DEFAULT=0
@@ -149,7 +148,7 @@ GRUB_CMDLINE_LINUX=""
 GRUB_TERMINAL=console
 EOF
 
-chroot $MNT_DIR update-grub || fail "cannot update grub"
+chroot $MNT_DIR sudo -i update-grub || fail "cannot update grub"
 chroot $MNT_DIR apt-get clean || fail "unable to clean apt cache"
 
 sed -i "s|${DISK}p1|/dev/vda1|g" $MNT_DIR/boot/grub/grub.cfg
@@ -162,7 +161,7 @@ do
 done
 
 echo "Finishing grub installation..."
-grub-install $DISK --root-directory=$MNT_DIR --modules="biosdisk part_msdos" || fail "cannot reinstall grub"
+grub-install $DISK --target=i386-pc --root-directory=$MNT_DIR --modules="biosdisk part_msdos" || fail "cannot reinstall grub"
 
 echo "SUCCESS!"
 clean_debian
